<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HaroohiePals.IO\HaroohiePals.IO.csproj" />
    <ProjectReference Include="..\HaroohiePals.KCollision\HaroohiePals.KCollision.csproj" />
    <ProjectReference Include="..\HaroohiePals.MarioKart\HaroohiePals.MarioKart.csproj" />
    <ProjectReference Include="..\HaroohiePals.Math\HaroohiePals.Mathematics.csproj" />
    <ProjectReference Include="..\HaroohiePals.Nitro.NitroSystem\HaroohiePals.Nitro.NitroSystem.csproj" />
    <ProjectReference Include="..\HaroohiePals.Nitro\HaroohiePals.Nitro.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\MapObjPlaceholderModels.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MapObjPlaceholderModels.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\MapObjPlaceholderModels.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MapObjPlaceholderModels.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
