//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaroohiePals.MarioKartToolbox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaroohiePals.MarioKartToolbox.Resources.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Window][DockSpaceViewport_11111111]
        ///Pos=0,43
        ///Size=1400,857
        ///Collapsed=0
        ///
        ///[Window][Debug##Default]
        ///Pos=60,60
        ///Size=400,400
        ///Collapsed=0
        ///
        ///[Window][Test Window]
        ///Pos=1019,474
        ///Size=381,426
        ///Collapsed=0
        ///DockId=0x00000004,1
        ///
        ///[Window][Properties]
        ///Pos=1019,474
        ///Size=381,426
        ///Collapsed=0
        ///DockId=0x00000004,0
        ///
        ///[Window][Map Data Explorer]
        ///Pos=1019,43
        ///Size=381,429
        ///Collapsed=0
        ///DockId=0x00000001,0
        ///
        ///[Window][Archive]
        ///Pos=1019,43
        ///Size=381,429
        ///Collapsed=0
        ///DockId=0x00000001,1
        ///
        ///[Window][Top-down]
        ///P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImGuiIni {
            get {
                return ResourceManager.GetString("ImGuiIni", resourceCulture);
            }
        }
    }
}
