//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaroohiePals.MarioKartToolbox.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shaders {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shaders() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HaroohiePals.MarioKartToolbox.Resources.Shaders", typeof(Shaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FogPassFragment {
            get {
                return ResourceManager.GetString("FogPassFragment", resourceCulture);
            }
        }
        
        internal static string FogPassVertex {
            get {
                return ResourceManager.GetString("FogPassVertex", resourceCulture);
            }
        }
        
        internal static string KartFragment {
            get {
                return ResourceManager.GetString("KartFragment", resourceCulture);
            }
        }
        
        internal static string KartIntelFragment {
            get {
                return ResourceManager.GetString("KartIntelFragment", resourceCulture);
            }
        }
        
        internal static string KartVertex {
            get {
                return ResourceManager.GetString("KartVertex", resourceCulture);
            }
        }
        
        internal static string KclOctreeCubeFragment {
            get {
                return ResourceManager.GetString("KclOctreeCubeFragment", resourceCulture);
            }
        }
        
        internal static string KclOctreeCubeVertex {
            get {
                return ResourceManager.GetString("KclOctreeCubeVertex", resourceCulture);
            }
        }
        
        internal static string KclPrismFragment {
            get {
                return ResourceManager.GetString("KclPrismFragment", resourceCulture);
            }
        }
        
        internal static string KclPrismVertex {
            get {
                return ResourceManager.GetString("KclPrismVertex", resourceCulture);
            }
        }
        
        internal static string NkmAreaFragment {
            get {
                return ResourceManager.GetString("NkmAreaFragment", resourceCulture);
            }
        }
        
        internal static string NkmAreaVertex {
            get {
                return ResourceManager.GetString("NkmAreaVertex", resourceCulture);
            }
        }
    }
}
