//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaroohiePals.Graphics3d.OpenGL.Renderers.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Models {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HaroohiePals.Graphics3d.OpenGL.Renderers.Resources.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ArrowTexture {
            get {
                object obj = ResourceManager.GetObject("ArrowTexture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BoxTexture {
            get {
                object obj = ResourceManager.GetObject("BoxTexture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CubeObj {
            get {
                object obj = ResourceManager.GetObject("CubeObj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] QuadObj {
            get {
                object obj = ResourceManager.GetObject("QuadObj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SphereObj {
            get {
                object obj = ResourceManager.GetObject("SphereObj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TestTexture {
            get {
                object obj = ResourceManager.GetObject("TestTexture", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
