//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaroohiePals.Graphics3d.OpenGL.Renderers.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shaders {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shaders() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HaroohiePals.Graphics3d.OpenGL.Renderers.Resources.Shaders", typeof(Shaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BoxFragment {
            get {
                return ResourceManager.GetString("BoxFragment", resourceCulture);
            }
        }
        
        internal static string BoxIntelFragment {
            get {
                return ResourceManager.GetString("BoxIntelFragment", resourceCulture);
            }
        }
        
        internal static string BoxVertex {
            get {
                return ResourceManager.GetString("BoxVertex", resourceCulture);
            }
        }
        
        internal static string CircleFragment {
            get {
                return ResourceManager.GetString("CircleFragment", resourceCulture);
            }
        }
        
        internal static string CircleVertex {
            get {
                return ResourceManager.GetString("CircleVertex", resourceCulture);
            }
        }
        
        internal static string DotFragment {
            get {
                return ResourceManager.GetString("DotFragment", resourceCulture);
            }
        }
        
        internal static string DotVertex {
            get {
                return ResourceManager.GetString("DotVertex", resourceCulture);
            }
        }
        
        internal static string GridFragment {
            get {
                return ResourceManager.GetString("GridFragment", resourceCulture);
            }
        }
        
        internal static string GridVertex {
            get {
                return ResourceManager.GetString("GridVertex", resourceCulture);
            }
        }
        
        internal static string LineFragment {
            get {
                return ResourceManager.GetString("LineFragment", resourceCulture);
            }
        }
        
        internal static string LineVertex {
            get {
                return ResourceManager.GetString("LineVertex", resourceCulture);
            }
        }
        
        internal static string QuadFragment {
            get {
                return ResourceManager.GetString("QuadFragment", resourceCulture);
            }
        }
        
        internal static string QuadVertex {
            get {
                return ResourceManager.GetString("QuadVertex", resourceCulture);
            }
        }
    }
}
